### ISSUE TITLE
shares profile

### ISSUE THREAD

**Issue by WiredLife** [tuya-cloudcutter/tuya-cloudcutter.github.io#10]
LSC 3004164 970721 v1.2 E14 Candle RGB CCT is flashable via the LSC 3004919 970706 v1.1-Lightbulb profile

**Comment by Cossid** [comment]
We only add full profiles with schemas in order to be 'cuttable' compatible with tuya firmware.  We don't add additional profiles for compatible things to flash from, as you can just use the existing profiles if that is your goal.

**Comment by WiredLife** [comment]
i mean, you can copy the LSC 3004919 970706 v1.1-Lightbulb profile to "LSC 3004164 970721 v1.2 E14 Candle RGB CCT"
i test everything only with option 2 (flash) because i have no goal to just cut
but i think, when flash is working, the cut will also work

**Comment by Cossid** [comment]
The point is, that device may have a different schema and not work correctly with cut Tuya firmware.  The profile may cut them both, but the bulbs may not operate the same (different schemas/configurations).

We know they are compatible for flashing, but cloudcutter also supports just cutting, and that needs to be confirmed working.

**Comment by WiredLife** [comment]
i tried to dump the candle rgb firmware via lightleak and cloudcutter android app but i fail
maybe i will try again later, but the only one which has the original firmware is currently in use, the other has flashed openbk
