### ISSUE TITLE
LSC 2578539 970719 v.1.0 A60 E27 RGB CCT profile

### ISSUE THREAD

**Issue by WiredLife** [tuya-cloudcutter/tuya-cloudcutter.github.io#11]
please add ;)
[lsc-2578539-970719-v.1.0-a60-e27-rgb-cct.zip](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/10296889/lsc-2578539-970719-v.1.0-a60-e27-rgb-cct.zip)

**Comment by Cossid** [comment]
This profile already exists as `LSC 2578539 970719 White And Color Ambiance E27 806Lumen`
