### ISSUE TITLE
Luminary LK20040021 profile request + JSON error

### ISSUE THREAD

**Issue by GuidoMeinke** [tuya-cloudcutter/tuya-cloudcutter.github.io#3]
got a dump of my device VIA [bk7231tools](https://github.com/tuya-cloudcutter/bk7231tools)

Are you able to do a profile, please? 
[Lumary-Smart-Slim-Panel-Light-A3.zip](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/10171245/Lumary-Smart-Slim-Panel-Light-A3.zip)

**Comment by Cossid** [comment]
Can you please post a link to the product as well?

**Comment by Cossid** [comment]
Device has been added as Luminary LK20040021 Recessed Downlight

**Comment by GuidoMeinke** [comment]
Hello,

it's me again, this profile runs into an error:

Traceback (most recent call last):
  File "/src/get_input.py", line 247, in <module>
    cli(obj={})
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/src/get_input.py", line 226, in choose_profile
    device, profile = load_profile(profile_dir)
  File "/src/get_input.py", line 105, in load_profile
    data = json.load(f)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 9 column 1 (char 8)
Failed to choose a profile, please run this script again

I'm sry for my stupidness but the other profiles are doing great (start and looking for AP etc.)

**Comment by Cossid** [comment]
This doesn't appear to be an error with the profile, but just running in general.

Can you please post the command you are running (omitting any private data) and a full log of the output, not just the error?

**Comment by GuidoMeinke** [comment]
Hello, it's me again, have not fixed the problem in between.
How can I create a log of the output? This is all I have:


~/tuya-cloudcutter$ ./run_detach.sh
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
Building cloudcutter docker image..
Sending build context to Docker daemon  23.96MB
Step 1/10 : FROM python:3.9-slim-buster AS base
 ---> 70fa42c638b3
Step 2/10 : RUN apt-get -qq update && apt-get install -qy --no-install-recommends git hostapd rfkill dnsmasq build-essential libssl-dev iproute2 mosquitto
 ---> Using cache
 ---> 7bbc957b42a0
Step 3/10 : FROM base AS python-deps
 ---> 7bbc957b42a0
Step 4/10 : RUN pip install --upgrade pipenv
 ---> Using cache
 ---> 7a5ce269e500
Step 5/10 : COPY src/Pipfile /src/
 ---> Using cache
 ---> 4d7e39b87d78
Step 6/10 : COPY src/Pipfile.lock /src/
 ---> Using cache
 ---> e7d30a2e9dae
Step 7/10 : RUN cd /src && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
 ---> Using cache
 ---> 4ca8553f0be7
Step 8/10 : FROM python-deps AS cloudcutter
 ---> 4ca8553f0be7
Step 9/10 : COPY src /src
 ---> Using cache
 ---> 385cfd60f975
Step 10/10 : WORKDIR /src
 ---> Using cache
 ---> b4774db07962
Successfully built b4774db07962
Successfully tagged cloudcutter:latest
Successfully built docker image
[?] How do you want to choose the device?: From device-profiles (i.e. custom profile)
   By manufacturer/device name
   By firmware version and name
 > From device-profiles (i.e. custom profile)

[?] Select device profile: luminary-lk20040021-recessed-downlight
   lightway-smart-al2017-tgts
 > luminary-lk20040021-recessed-downlight
   tuya-generic-lv300-lv400-lv480-lv600st-led-square-led-ceiling-light

Traceback (most recent call last):
  File "/src/get_input.py", line 247, in <module>
    cli(obj={})
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/src/get_input.py", line 226, in choose_profile
    device, profile = load_profile(profile_dir)
  File "/src/get_input.py", line 105, in load_profile
    data = json.load(f)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 9 column 1 (char 8)
Failed to choose a profile, please run this script again

**Comment by kuba2k2** [comment]
Try choosing the profile by manufacturer, instead of "from device profiles".

**Comment by Cossid** [comment]
Can you please clarify if `~/tuya-cloudcutter$ ./run_detach.sh` is exactly what you ran, or if you redacted information.

If that's exactly what you ran, you must supply a ssid and password for run_detach.  See `./run_detach.sh -h` for more details.
If you removed that and ran with the necessary information, you may need to run elevated.

**Comment by kuba2k2** [comment]
That error occurs because you have a non-JSON file in the custom profile directory. Try clearing the directory manually, backing up everything that you might need. Then run it again and use profile by manufacturer/model.

Labelled as a bug as it needs to be fixed.

**Comment by GuidoMeinke** [comment]
~/tuya-cloudcutter$ ./run_detach.sh
Checking TCP port 80... [sudo] Passwort für guido: 
Available.
Checking TCP port 443... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
Building cloudcutter docker image..
Sending build context to Docker daemon  24.39MB
Step 1/10 : FROM python:3.9-slim-buster AS base
 ---> 70fa42c638b3
Step 2/10 : RUN apt-get -qq update && apt-get install -qy --no-install-recommends git hostapd rfkill dnsmasq build-essential libssl-dev iproute2 mosquitto
 ---> Using cache
 ---> 7bbc957b42a0
Step 3/10 : FROM base AS python-deps
 ---> 7bbc957b42a0
Step 4/10 : RUN pip install --upgrade pipenv
 ---> Using cache
 ---> 7a5ce269e500
Step 5/10 : COPY src/Pipfile /src/
 ---> Using cache
 ---> 4d7e39b87d78
Step 6/10 : COPY src/Pipfile.lock /src/
 ---> Using cache
 ---> e7d30a2e9dae
Step 7/10 : RUN cd /src && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
 ---> Using cache
 ---> 4ca8553f0be7
Step 8/10 : FROM python-deps AS cloudcutter
 ---> 4ca8553f0be7
Step 9/10 : COPY src /src
 ---> Using cache
 ---> 385cfd60f975
Step 10/10 : WORKDIR /src
 ---> Using cache
 ---> b4774db07962
Successfully built b4774db07962
Successfully tagged cloudcutter:latest
Successfully built docker image
[?] How do you want to choose the device?: By manufacturer/device name
 > By manufacturer/device name
   By firmware version and name
   From device-profiles (i.e. custom profile)

[?] Select the brand of your device: Luminary
   LEDVANCE
   LSC
   Lampsero
   Lenovo
   Lightway
   Lonsonho
 > Luminary
   MOES
   MartinJerry
   Merkury
   Minoston
   Mlambert
   Mycket

[?] Select the article number of your device: LK20040021 Recessed Downlight
 > LK20040021 Recessed Downlight

[?] Select the firmware version and name: 2.9.16 - BK7231T / oem_bk7231s_light_ty
 > 2.9.16 - BK7231T / oem_bk7231s_light_ty

==> Toggle Tuya device's power off and on again 6 times, with ~1 sec pauses in between, to enable AP mode. Repeat if your device's SSID doesn't show up within ~30 seconds. For smart plugs long press the reset button on the device for about 5 seconds. See https://support.tuya.com/en/help/_detail/K9hut3w10nby8 for more information.
Scanning for known AP SSID prfixes: "A-" "atomi-smart-" "Geeni-" "Globe Suite-" "GRID-" "iHome-" "LDV SMART+-" "Merkury-" "Nexxt Home-" "SL-CreeLighting-" "SL-FLSNT-" "SmartLife-" "TreatLife-SL-" "UltraPro-" "Woox-" 
.........................................................................................................................................................

using choose profil by manufacturer seems to working but he does not recognize the correct AP Lumary-43C3

**Comment by Cossid** [comment]
Added the Luminary- AP prefix, please do a `git pull` and run again.

**Comment by GuidoMeinke** [comment]
pulled again and cloudcutter does not recognize the AP i can see it in the with my smartphone and even in the wifi list on my pc


==> Toggle Tuya device's power off and on again 6 times, with ~1 sec pauses in between, to enable AP mode. Repeat if your device's SSID doesn't show up within ~30 seconds. For smart plugs long press the reset button on the device for about 5 seconds. See https://support.tuya.com/en/help/_detail/K9hut3w10nby8 for more information.
Scanning for known AP SSID prfixes: "A-" "atomi-smart-" "Geeni-" "Globe Suite-" "GRID-" "iHome-" "LDV SMART+-" "Luminary-" "Merkury-" "Nexxt Home-" "SL-CreeLighting-" "SL-FLSNT-" "SmartLife-" "TreatLife-SL-" "UltraPro-" "Woox-" 
.....................................................................................................................................................................................................................................................................................................................................

**Comment by GuidoMeinke** [comment]
ok, i've found the AP, but.... it won't connect.
==> Toggle Tuya device's power off and on again 6 times, with ~1 sec pauses in between, to enable AP mode. Repeat if your device's SSID doesn't show up within ~30 seconds. For smart plugs long press the reset button on the device for about 5 seconds. See https://support.tuya.com/en/help/_detail/K9hut3w10nby8 for more information.
Scanning for known AP SSID prfixes: "A-" "atomi-smart-" "Geeni-" "Globe Suite-" "GRID-" "iHome-" "LDV SMART+-" "Lumary-" "Merkury-" "Nexxt Home-" "SL-CreeLighting-" "SL-FLSNT-" "SmartLife-" "TreatLife-SL-" "UltraPro-" "Woox-" 
.Found access point name: "Lumary-43C3", trying to connect..
Gerät »wlp3s0« wurde erfolgreich mit »75dba659-89b8-4e5b-94fd-08c00ed6821f« aktiviert.
..Found access point name: "Lumary-43C3", trying to connect..
Gerät »wlp3s0« wurde erfolgreich mit »75dba659-89b8-4e5b-94fd-08c00ed6821f« aktiviert.
..Found access point name: "Lumary-43C3", trying to connect..
Gerät »wlp3s0« wurde erfolgreich mit »75dba659-89b8-4e5b-94fd-08c00ed6821f« aktiviert.
..Found access point name: "Lumary-43C3", trying to connect..
Gerät »wlp3s0« wurde erfolgreich mit »75dba659-89b8-4e5b-94fd-08c00ed6821f« aktiviert.
..Found access point name: "Lumary-43C3", trying to connect..
Gerät »wlp3s0« wurde erfolgreich mit »75dba659-89b8-4e5b-94fd-08c00ed6821f« aktiviert.
Error, could not connect to SSID.
Failed to connect, please run this script again
