### ISSUE TITLE
I have a Taloya Smart LED Ceiling Light with a WB3S

### ISSUE THREAD

**Issue by kellcomnet2** [tuya-cloudcutter/tuya-cloudcutter.github.io#30]
I have a Taloya Smart LED Ceiling Light with a WB3S chip.
Not sure if the product name is Galaxy AI-Plus or Galaxy AI yet as I have not connected it to power.

I have a USB UART adapter coming next week. What do you need from me to get this added. I have a Raspberry Pi 3b sitting on a shelf ready to go. I am comfortable with cli and can usually follow instructions.

https://a.co/d/j0DJPFU

**Comment by Cossid** [comment]
Depending on your goal, you may not need USB UART.  If you are planning on flashing 3rd party firmware, there is likely already a compatible profile available, you just need to find your firmware version, and see if one matches/works.  Being a light, it's likely to share a profile with another bulb or ceiling light like the Hykolity ceiling light.  You can find out what firmware your device has by following the instructions here: https://github.com/tuya-cloudcutter/tuya-cloudcutter/wiki/FAQ#how-do-i-find-out-what-firmware-version-my-device-has

If your goal is just to cut it and use the Tuya firmware, we'd need a device dump, instructions can be found here: https://github.com/tuya-cloudcutter/tuya-cloudcutter#device-dumps
