### ISSUE TITLE
is device compatible for expoite?

### ISSUE THREAD

**Issue by 12christiaan** [tuya-cloudcutter/tuya-cloudcutter.github.io#34]
Hi all,

- how do i know if a device can use this tool?
- how do i find out (with out opening) what chip is inside?
I did search the list of device, but did not find this one. 

Product Name		LSC SMART Connect A60 RGB-CCT / 970714 9w 806lm
Mac:			68:57:2d:4f:xx:xx (Manufacturer: Tuya Smart Inc.)
Device update:	Main V6.1.7

**Comment by 12christiaan** [comment]
thanks for your reaction.
So i did open the bulb.
The chip is a WR3L ??

![IMG_20230304_173234](https://user-images.githubusercontent.com/251693/223144030-8ee384a6-fa2c-42b8-91f0-c53ae477aa88.jpg)
![IMG_20230306_154329](https://user-images.githubusercontent.com/251693/223144036-5c963708-959e-403b-9286-e2d1c2c755bb.jpg)
![IMG_20230306_154540](https://user-images.githubusercontent.com/251693/223144041-8a3247b2-2a28-40a0-a7bb-5c1f5c2b508b.jpg)
![IMG_20230306_154548](https://user-images.githubusercontent.com/251693/223144043-013a7ba3-0be0-4e2a-ab98-cd4d5b77ca92.jpg)

**Comment by Cossid** [comment]
WR3L is Realtek and therefore incompatible with Tuya-CloudCutter.

WR3L is Realtek RTL8710BX (Ameba-Z), and is compatible with ESPHome via LibreaTuya if you are able to serial flash.  Closing this issue as there is nothing further Tuya-CloudCutter can currently do for this device.
