### ISSUE TITLE
new device: Hombli_HBSS-0209-Smart-Socket-B2030248-Energy-Plug

### ISSUE THREAD

**Issue by 12christiaan** [tuya-cloudcutter/tuya-cloudcutter.github.io#35]
i took a dump and run profile_builder on this device.
Hombli Smart Socket (+ energy)
Product Name		Hombli Smart Socket
Model:			HBSS-0209 Smart socket   B2030248
Device update:	Main V 1.0.2

Files in next post, to late.. did not see how to upload first. LOL.
now i have these file, how do i flash them to the device? what file goes where?

**Comment by 12christiaan** [comment]
[Hombli_HBSS-0209-Smart-Socket-B2030248-Energy-Plug.zip](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/10926322/Hombli_HBSS-0209-Smart-Socket-B2030248-Energy-Plug.zip)
here are the files.
how can i use them local?

**Comment by Cossid** [comment]
I have added this to the API as `Hombli HBSS-0209 Smart Socket B2030248 Energy Plug`

To use files locally, you create a folder in the `device-profiles` folder and copy the `.json` file from the device and profile folder into it, and then use `-p <foldername>`
