### ISSUE TITLE
tuya-generic-80a-energy-meter.json has no GPIO pin out

### ISSUE THREAD

**Issue by trinami** [tuya-cloudcutter/tuya-cloudcutter.github.io#64]
Hello, could you please add a pin configuration to this json?
Currently I couldn't use it because no pins were defined.
Thank you

**Comment by trinami** [comment]
Found some dumps, but unfortunately its all greek for me :/  https://www.elektroda.com/rtvforum/topic3946128.html

**Comment by Cossid** [comment]
There is no configuration json included with a device like that.  That is a Tuya MCU device which just uses uart at baud 9600 on pins RX1/TX1, then you must configure the DPIDs that are transferred over that, but at also not included in configurations.

See the TuyaMCU documentation for whichever firmware you're using.  The DPIDs are in the schema section, but you'll have to convert/map them manually (looks like it's mostly done in that forum post you posted).
