### ISSUE TITLE
Profile for Merkury Innovations MI-EW010-999WW RGBW led strip

### ISSUE THREAD

**Issue by Prof256** [tuya-cloudcutter/tuya-cloudcutter.github.io#75]
[profile-classic.zip](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/12456017/profile-classic.zip)
 The Firmware is marked 1.0.4. The current profiles for Firmware 0.0.2 and 0.0.3 did not work for me.

**Comment by Cossid** [comment]
Added as `Merkury Innovations MI-EW010-999WW LED Strip v1.0.4`
