### ISSUE TITLE
Tuya cloudcutter failing and crashing.

### ISSUE THREAD

**Issue by ide4you** [tuya-cloudcutter/tuya-cloudcutter.github.io#9]
I installed and setup tuya cloudcutter to use for flashing beken chips but have not gone past it building docker image because it crashes when it gets to loading options. Below is the entire 

*****************************************************************
user@Enugu:~/Downloads/BUILD/tuya-cloudcutter$  ./tuya-cloudcutter.sh -s UzdomW_40 Mum15w0rd -p device-profiles/gosund-sw5-a-v2.1-smart-switch.json 
[sudo] password for uzor: 
Checking UDP port 53... Occupied by systemd-resolve with PID 16781.
Port 53 is needed to resolve DNS queries
Do you wish to terminate systemd-resolve? [y/N] y
Attempting to stop systemd-resolved.service
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
Building cloudcutter docker image..
Sending build context to Docker daemon  23.53MB
Step 1/10 : FROM python:3.9-slim-buster AS base
 ---> 8a1ad5297c50
Step 2/10 : RUN apt-get -qq update && apt-get install -qy --no-install-recommends git hostapd rfkill dnsmasq build-essential libssl-dev iproute2 mosquitto
 ---> Using cache
 ---> 156adb17088b
Step 3/10 : FROM base AS python-deps
 ---> 156adb17088b
Step 4/10 : RUN pip install --upgrade pipenv
 ---> Using cache
 ---> 0f8c68a9aa79
Step 5/10 : COPY src/Pipfile /src/
 ---> Using cache
 ---> 881228475eba
Step 6/10 : COPY src/Pipfile.lock /src/
 ---> Using cache
 ---> e29afb20c3b9
Step 7/10 : RUN cd /src && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
 ---> Using cache
 ---> f9671668b2fe
Step 8/10 : FROM python-deps AS cloudcutter
 ---> f9671668b2fe
Step 9/10 : COPY src /src
 ---> Using cache
 ---> ad62037e3423
Step 10/10 : WORKDIR /src
 ---> Using cache
 ---> 58f63318d66b
Successfully built 58f63318d66b
Successfully tagged cloudcutter:latest
Successfully built docker image
Loading options, please wait...
Traceback (most recent call last):
  File "/src/get_input.py", line 252, in <module>
    cli(obj={})
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/src/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/src/get_input.py", line 197, in write_profile
    if not (device and profile):
UnboundLocalError: local variable 'device' referenced before assignment
Failed to choose a profile, please run this script again

**Comment by Cossid** [comment]
> -p device-profiles/gosund-sw5-a-v2.1-smart-switch.json

Is incorrect.  If you're creating a custom profile, you must place it in a directory in `/device/profiles` and supply the name of that directory to the `-p` parameter.
